fullnameOverride: argocd
crds:
  install: true
  keep: true

configs:
  repositories: 
    # istio-helm-repo:
    #   url: https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts
    #   name: istio.io
    #   type: helm
    private-helm-repo:
      url: http://crommie.chickenkiller.com:8088/root/gitops-config.git
      name: gitops
      password: glpat-Uic4--3K6TmLkAMH1s31
      username: argo
    # private-repo:
    #   url: https://github.com/argoproj/private-repo
  secret:
    argocdServerAdminPassword: "$2a$10$jQssWq5KLmyoXONBbJbPnOwnVLcNVzd19X.ejAxl6uZH5T6U/kMYu"

server:
  ingress:
    enabled: trues
    annotations: 
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    hosts:
      - argo-cd.net
    paths:
      - /
    pathType: Prefix