version: '3.9'

services:
  app:
    image: "${APP_IMAGE}"
    container_name: "uasset-app"
    restart: on-failure
    depends_on:
       db:
          condition: service_healthy

    environment:
      PORTFOLIO_MONGO_DB_URI:  "mongodb://${DB_USERNAME}:${DB_PASSWORD}@db:27017/develeap_portfolio"
      PORTFOLIO_MONGO_DB_HOST: db
      PORTFOLIO_MONGO_DB_PORT: 27017
      PORTFOLIO_MONGO_DB_NAME: "develeap_portfolio"
    networks:
      - portfolio_prod_net
    

  db:
    container_name: mongodb
    image: bitnami/mongodb:latest
    environment:
      MONGODB_USERNAME: "${DB_USERNAME}"
      MONGODB_PASSWORD: "${DB_PASSWORD}"
      MONGODB_DATABASE: "${DB_NAME}"
      MONGODB_ROOT_USERNAME: "${DB_ROOT_USERNAME}"
      MONGODB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

    healthcheck:
      test: ["CMD",  "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongodb_prod_data_container:/data/db
    networks:
      - portfolio_prod_net


  nginx:
    image: "${PROXY_APP_IMAGE}"
    container_name: uasset-proxy
    restart: on-failure
    ports:
      - "8076:80"
    depends_on:
        app:
          condition: service_healthy
    networks:
      - portfolio_prod_net


volumes:
  mongodb_prod_data_container:

networks:
  portfolio_prod_net: