apiVersion: apps/v1
kind: Deployment
metadata:
  name: rando
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rando
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: rando
    spec:
      containers:
      - name: rando
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        envFrom:
          - configMapRef:
              name: rando-config-rando
        resources:
          {{- toYaml .Values.resources | nindent 12 }}