apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    path: ./gitops/manifest/denpends/cert-manager
    repoURL: 'https://github.com/worlakodzo/worlako-develeap-porfolio.git'
    targetRevision: HEAD
  project: default
  # Sync policy
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true