apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ./gitops/manifest/denpends/sealed-secrets
    repoURL: 'https://github.com/worlakodzo/worlako-develeap-porfolio.git'
    targetRevision: HEAD
  project: default
  # Sync policy
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true