# https://blog.ediri.io/kube-prometheus-stack-and-argocd-23-how-to-remove-a-workaround
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: ./gitops/manifest/denpends/monitoring/kube-prometheus-stack
    repoURL: 'https://github.com/worlakodzo/worlako-develeap-porfolio.git'
    targetRevision: HEAD
    helm:
      skipCrds: true
    # chart: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
