apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ./gitops/manifest/my-crds/other-apps
    repoURL: 'https://github.com/worlakodzo/worlako-develeap-porfolio.git'
    targetRevision: HEAD
  project: default
  # Sync policy
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
      allowEmpty: false