fullnameOverride: cert-manager
installCRDs: true

metrics:
  enabled: true
  podAnnotations:
    prometheus.io/path: "/metrics"
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.controller.containerPort }}"
  serviceMonitor:
    path: /metrics
    targetPort: 9402
    enabled: true#
    namespace: monitoring
    interval: 60s
    scrapeTimeout: 30s
    honorLabels: true