apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  type: {{ .Values.service.type }}
  selector:
    app: kibana
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.port }}
      targetPort: 5601