apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: {{ .Values.service.type }}
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.port }}
      targetPort: 9200